// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace BlazorBoats.Models
{
    public partial class Builder
    {
        public const string Codename = "builder";
        public const string BuilderNameCodename = "builder_name";
        public const string LocationCodename = "location";

        public string BuilderName { get; set; }
        public string Location { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}