// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace BlazorBoats.Models
{
    public partial class DinghyClass
    {
        public const string Codename = "dinghy_class";
        public const string AssociationNameCodename = "association_name";
        public const string AssociationWebsiteCodename = "association_website";
        public const string BoatLengthCodename = "boat_length";
        public const string BuildersCodename = "builders";
        public const string ClassNameCodename = "class_name";
        public const string ClassSymbolCodename = "class_symbol";
        public const string ClassificationCodename = "classification";
        public const string DesignDateCodename = "design_date";
        public const string DesignTypeCodename = "design_type";
        public const string ImageCodename = "image";
        public const string InformationCodename = "information";
        public const string PyNumberCodename = "py_number";
        public const string PyTypeCodename = "py_type";
        public const string SeoSocialPageDescriptionCodename = "seo_social__page_description";
        public const string SeoSocialPageTitleCodename = "seo_social__page_title";
        public const string SeoSocialSharedImageCodename = "seo_social__shared_image";

        public string AssociationName { get; set; }
        public string AssociationWebsite { get; set; }
        public string BoatLength { get; set; }
        public IEnumerable<object> Builders { get; set; }
        public IEnumerable<TaxonomyTerm> Classification { get; set; }
        public string ClassName { get; set; }
        public IEnumerable<Asset> ClassSymbol { get; set; }
        public decimal? DesignDate { get; set; }
        public IEnumerable<TaxonomyTerm> DesignType { get; set; }
        public IEnumerable<Asset> Image { get; set; }
        public string Information { get; set; }
        public decimal? PyNumber { get; set; }
        public IEnumerable<MultipleChoiceOption> PyType { get; set; }
        public string SeoSocialPageDescription { get; set; }
        public string SeoSocialPageTitle { get; set; }
        public IEnumerable<Asset> SeoSocialSharedImage { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}