// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace BlazorBoats.Models
{
    public partial class LanguagePack
    {
        public const string Codename = "language_pack";
        public const string GenericHomeCodename = "generic_home";
        public const string GenericSelectlanguageCodename = "generic_selectlanguage";
        public const string NavigationViewcategoryCodename = "navigation_viewcategory";
        public const string PageClassBuildersCodename = "page_class_builders";
        public const string PageClassificationTitleCodename = "page_classification_title";

        public string GenericHome { get; set; }
        public string GenericSelectlanguage { get; set; }
        public string NavigationViewcategory { get; set; }
        public string PageClassBuilders { get; set; }
        public string PageClassificationTitle { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}